model_name: 'u-net'

model:
  in_channels: 2
  out_channels: 1

dataset:
  batch_size: 64
  num_workers: 16
  seq_len_in: 1
  seq_len_out: 0
  stride: 1
  sevir_root_dir: '/home/datalab/big-disk/SEVIR/'
  x_img_types:
    - 'ir069'
    - 'ir107'
  y_img_types:
    - 'vil'
  preprocess: true
  normalization_method: 'sevir'
  downsample:
    vis: 4
    vil: 2
  upsample:
    lght: 4
  start_date: [2018, 1, 1]
  end_date: [2019, 12, 31]

training:
  check_val_every_n_epoch: 1
  max_epochs: 50
